### ISSUE TITLE
Ability to Delete Todo Items Individually

### ISSUE THREAD

**Issue by mlsaito** [toti1212/todo-cli#11]
### Description

Hi there! First of all thanks for this package! It would be nice if there's an ability to delete todo items individually as I accidentally added an incorrect item by mistake (and couldn't find a way to delete that single one).

Or maybe there's already a way, please do let me know. Thank you!

### To-Do

- [ ] Add an ability to delete items one by one.

**Comment by toti1212** [comment]
Hi @mlsaito 👋! Thanks for giving it a try!

I was a bit messy because I just started this feature yesterday 😅 I forgot to update the milestone and the project status. It will be part of the v1.0. I have been working extending the `clean` command to delete a single item from the todo list. Example:

```bash
$ todo clean 1
$ todo cl 1
```

Then we can discuss if it's ok to get only the command `clean` or a new one it's better, like `remove` `rm` (I think it's cooler).

🚨On the other hand, a new command was added (v0.9.3): `edit`. You can edit a typo if you needed.

When I finish it I'll release a new version (v.0.9.4) 😎 Stay tuned!

**Comment by mlsaito** [comment]
@toti1212 Heya! Yes that would suffice for the meantime. If it's single deletion, on my humble opinion, I think it would be better to have a separate command (like what you mentioned `remove` or `rm`) as `clean` is sort of tied to cleaning a group or a list. :)
